// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherDetailsAPI.Models;

namespace WeatherDetailsAPI.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20210522062022_firstMig")]
    partial class firstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherDetailsAPI.Models.Weather", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Forcast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HighTemp")
                        .HasColumnType("real");

                    b.Property<float>("LowTemp")
                        .HasColumnType("real");

                    b.HasKey("City");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
